// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DAL.Migrations
{
    [DbContext(typeof(AddressBookContext))]
    [Migration("20200712175516_addPhoneNum")]
    partial class addPhoneNum
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn)
                .HasAnnotation("ProductVersion", "3.1.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("DAL.Models.Contact", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string[]>("PhoneNum")
                        .HasColumnType("text[]");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateOfBirth = new DateTime(1990, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "John Johnes",
                            PhoneNum = new[] { "0992221134", "0952211478", "0995135647" }
                        },
                        new
                        {
                            Id = 2,
                            DateOfBirth = new DateTime(1990, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ivan Blatazar",
                            PhoneNum = new[] { "099578681" }
                        },
                        new
                        {
                            Id = 3,
                            DateOfBirth = new DateTime(1990, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ivana Ivanović",
                            PhoneNum = new[] { "0992221134", "0952211478", "0995135647" }
                        },
                        new
                        {
                            Id = 4,
                            DateOfBirth = new DateTime(1990, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ivanka Perić",
                            PhoneNum = new[] { "0992221134" }
                        },
                        new
                        {
                            Id = 5,
                            DateOfBirth = new DateTime(1990, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Iva Gordanić",
                            PhoneNum = new[] { "0992221134" }
                        },
                        new
                        {
                            Id = 6,
                            DateOfBirth = new DateTime(1990, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ivor Beleter",
                            PhoneNum = new[] { "0992221134", "0952211478" }
                        },
                        new
                        {
                            Id = 7,
                            DateOfBirth = new DateTime(1990, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Petar Kajić",
                            PhoneNum = new[] { "0992221134" }
                        },
                        new
                        {
                            Id = 8,
                            DateOfBirth = new DateTime(1990, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ingrid Budić",
                            PhoneNum = new[] { "0992221134" }
                        },
                        new
                        {
                            Id = 9,
                            DateOfBirth = new DateTime(1990, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Igor Igorić",
                            PhoneNum = new[] { "0992221134" }
                        },
                        new
                        {
                            Id = 10,
                            DateOfBirth = new DateTime(1990, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Valentino Valentić",
                            PhoneNum = new[] { "0992221134" }
                        },
                        new
                        {
                            Id = 11,
                            DateOfBirth = new DateTime(1990, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Barbara Ivković",
                            PhoneNum = new[] { "0992221134" }
                        },
                        new
                        {
                            Id = 12,
                            DateOfBirth = new DateTime(1990, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tea Teić",
                            PhoneNum = new[] { "0992221134" }
                        },
                        new
                        {
                            Id = 13,
                            DateOfBirth = new DateTime(1990, 6, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Viktor Draganić",
                            PhoneNum = new[] { "0992221134" }
                        });
                });

            modelBuilder.Entity("DAL.Models.ContactAddress", b =>
                {
                    b.Property<int>("ContactAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn);

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<int>("ContactId")
                        .HasColumnType("integer");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<int>("ZipCode")
                        .HasColumnType("integer");

                    b.HasKey("ContactAddressId");

                    b.HasIndex("ContactId")
                        .IsUnique();

                    b.ToTable("ContactAddress");

                    b.HasData(
                        new
                        {
                            ContactAddressId = 1,
                            Address = "Svetog Petra 2",
                            City = "Hvar",
                            ContactId = 1,
                            Country = "Hrvatska",
                            ZipCode = 55223
                        },
                        new
                        {
                            ContactAddressId = 2,
                            Address = "Zlarinska 6",
                            City = "Šibenik",
                            ContactId = 2,
                            Country = "Hrvatska",
                            ZipCode = 40235
                        },
                        new
                        {
                            ContactAddressId = 3,
                            Address = "Svetog Petra 2",
                            City = "Hvar",
                            ContactId = 3,
                            Country = "Hrvatska",
                            ZipCode = 55223
                        },
                        new
                        {
                            ContactAddressId = 4,
                            Address = "Svetog Petra 2",
                            City = "Hvar",
                            ContactId = 4,
                            Country = "Hrvatska",
                            ZipCode = 55223
                        },
                        new
                        {
                            ContactAddressId = 5,
                            Address = "Svetog Petra 2",
                            City = "Hvar",
                            ContactId = 5,
                            Country = "Hrvatska",
                            ZipCode = 55223
                        },
                        new
                        {
                            ContactAddressId = 6,
                            Address = "Svetog Petra 2",
                            City = "Hvar",
                            ContactId = 6,
                            Country = "Hrvatska",
                            ZipCode = 55223
                        },
                        new
                        {
                            ContactAddressId = 7,
                            Address = "Svetog Petra 2",
                            City = "Hvar",
                            ContactId = 7,
                            Country = "Hrvatska",
                            ZipCode = 55223
                        },
                        new
                        {
                            ContactAddressId = 8,
                            Address = "Svetog Petra 2",
                            City = "Hvar",
                            ContactId = 8,
                            Country = "Hrvatska",
                            ZipCode = 55223
                        },
                        new
                        {
                            ContactAddressId = 9,
                            Address = "Svetog Petra 2",
                            City = "Hvar",
                            ContactId = 9,
                            Country = "Hrvatska",
                            ZipCode = 55223
                        },
                        new
                        {
                            ContactAddressId = 10,
                            Address = "Svetog Petra 2",
                            City = "Hvar",
                            ContactId = 10,
                            Country = "Hrvatska",
                            ZipCode = 55223
                        },
                        new
                        {
                            ContactAddressId = 11,
                            Address = "Svetog Petra 2",
                            City = "Hvar",
                            ContactId = 11,
                            Country = "Hrvatska",
                            ZipCode = 55223
                        },
                        new
                        {
                            ContactAddressId = 12,
                            Address = "Svetog Petra 2",
                            City = "Hvar",
                            ContactId = 12,
                            Country = "Hrvatska",
                            ZipCode = 55223
                        },
                        new
                        {
                            ContactAddressId = 13,
                            Address = "Svetog Petra 2",
                            City = "Hvar",
                            ContactId = 13,
                            Country = "Hrvatska",
                            ZipCode = 55223
                        });
                });

            modelBuilder.Entity("DAL.Models.ContactAddress", b =>
                {
                    b.HasOne("DAL.Models.Contact", "Contact")
                        .WithOne("Address")
                        .HasForeignKey("DAL.Models.ContactAddress", "ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
